# Generated by Django 5.0.6 on 2025-06-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_role_alter_user_options_user_roles'),
        ('project', '0007_projectlayer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessible_projects',
            field=models.ManyToManyField(blank=True, related_name='users_with_access', to='project.project', verbose_name='پروژه\u200cهای قابل دسترسی'),
        ),
    ]
