# Generated by Django 5.0.6 on 2025-07-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_accessible_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='core.role', verbose_name='نقش\u200cها'),
        ),
    ]
