# Generated by Django 5.0.6 on 2025-11-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_update_userprojectrole'),
        ('project', '0013_alter_projectlayer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectrole',
            name='all_projects',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، این نقش برای همه پروژه\u200cها اعمال می\u200cشود', verbose_name='همه پروژه\u200cها'),
        ),
        migrations.AlterField(
            model_name='userprojectrole',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='پروژه\u200cهای مرتبط با این نقش', related_name='user_roles', to='project.project', verbose_name='پروژه\u200cها'),
        ),
        migrations.AlterField(
            model_name='userprojectrole',
            name='role',
            field=models.ForeignKey(help_text='نقش کاربر از لیست نقش\u200cهای تعریف شده', on_delete=django.db.models.deletion.CASCADE, related_name='user_project_roles', to='core.role', verbose_name='نقش'),
        ),
    ]
