# Generated by Django 5.0.6 on 2025-05-12 13:25

from django.db import migrations,models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometer_location', models.PositiveBigIntegerField(verbose_name='موقعیت کیلومتری')),
                ('start_kilometer', models.PositiveBigIntegerField(default=None, help_text='کیلومتر شروع اَبنیه', null=True, verbose_name='کیلومتر شروع')),
                ('end_kilometer', models.PositiveBigIntegerField(default=None, help_text='کیلومتر پایان اَبنیه', null=True, verbose_name='کیلومتر پایان')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='پروژه')),
                ('structure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.structuretype', verbose_name='نوع اَبنیه')),
            ],
            options={
                'verbose_name': 'اَبنیه پروژه',
                'verbose_name_plural': 'اَبنیه های پروژه',
                'ordering': ['kilometer_location'],
                'unique_together': {('project', 'structure_type')},
            },
        ),
    ]
