# Generated by Django 5.0.6 on 2025-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20250512_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstructure',
            name='end_kilometer',
            field=models.PositiveBigIntegerField(default=1, help_text='کیلومتر پایان اَبنیه', verbose_name='کیلومتر پایان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectstructure',
            name='start_kilometer',
            field=models.PositiveBigIntegerField(default=1, help_text='کیلومتر شروع اَبنیه', verbose_name='کیلومتر شروع'),
            preserve_default=False,
        ),
    ]
