# Generated by Django 5.0.6 on 2025-05-17 06:01

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projectstructure_end_kilometer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectex',
            name='date_joined',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ورود'),
        ),
    ]
