# Generated by Django 5.0.6 on 2025-05-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectex_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='distance',
            field=models.DecimalField(decimal_places=3, help_text='فاصله پروژه به کیلومتر', max_digits=20, verbose_name='فاصله (کیلومتر)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_kilometer',
            field=models.DecimalField(decimal_places=3, help_text='کیلومتر پایان پروژه', max_digits=20, verbose_name='کیلومتر پایان'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_kilometer',
            field=models.DecimalField(decimal_places=3, help_text='کیلومتر شروع پروژه', max_digits=20, verbose_name='کیلومتر شروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='width',
            field=models.DecimalField(decimal_places=3, help_text='عرض پروژه به متر', max_digits=20, verbose_name='عرض (متر)'),
        ),
    ]
