# Generated by Django 5.0.6 on 2025-05-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_distance_alter_project_end_kilometer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstructure',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'شروع نشده'), (1, 'در حال انجام'), (2, 'تکمیل شده'), (3, 'متوقف شده'), (4, 'لغو شده')], default=0, help_text='وضعیت ابینه را انتخاب کنید', verbose_name='وضعیت'),
        ),
    ]
