# Generated by Django 5.0.6 on 2025-06-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectstructure_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlayer',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'متغیر'), (1, 'ثابت')], default=1, help_text='حالت لایه را انتخاب کنید', verbose_name='حالت'),
        ),
    ]
