# Generated by Django 5.0.6 on 2025-07-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectlayer_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='distance',
        ),
        migrations.AddField(
            model_name='project',
            name='masafat',
            field=models.DecimalField(decimal_places=3, help_text='مسافت پروژه به کیلومتر', max_digits=20, null=True, verbose_name='مسافت (کیلومتر)'),
        ),
    ]
