# Generated by Django 5.0.6 on 2025-07-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_end_kilometer_alter_project_masafat_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectlayer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projectstructure',
            unique_together=set(),
        ),
    ]
