# Generated by Django 5.0.6 on 2025-07-21 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_project_end_kilometer_alter_project_masafat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hsse_manager',
            field=models.ForeignKey(blank=True, help_text='مسئول HSSE پروژه را انتخاب کنید', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hsse_managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='مسئول HSSE پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='lab_manager',
            field=models.ForeignKey(blank=True, help_text='مسئول آزمایشگاه پروژه را انتخاب کنید', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='مسئول آزمایشگاه'),
        ),
    ]
