# Generated by Django 5.0.6 on 2025-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_hsse_manager_project_lab_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlayer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'در انتظار آزمایش'), (1, 'در حال انجام'), (2, 'تکمیل شده'), (3, 'متوقف شده'), (4, 'لغو شده')], default=0, help_text='وضعیت لایه را انتخاب کنید', verbose_name='وضعیت'),
        ),
    ]
